steps:
# checkout git submodules
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git init
    git remote add origin https://github.com/SergeyKanzhelev/apmtips2.git
    git fetch --depth=1 origin $COMMIT_SHA
    git reset --hard FETCH_HEAD
    git submodule update --init --recursive
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/code', '.']
images: ['gcr.io/$PROJECT_ID/code']